project: rita_padufes20
device: cuda     # cuda | cpu
seed: 123

data:
  root: ./data/PAD-UFES-20
  metadata_csv: metadata.csv
  split_dir: ./data/PAD-UFES-20/splits
  img_size: 224
  num_workers: 2

train:
  model: vit_base
  k_folds: 3
  max_epochs: 100
  early_stopping_patience: 20
  batch_size: 32
  optimizer: adamw       # sgd | adamw
  lr: 1.0e-4
  momentum: 0.9
  weight_decay: 0.0001
  amp: true
  focal_loss:
    use: false
    alpha: 0.25
    gamma: 2.0
  pretrained: true

log:
  save_dir: ./reports
